* Load environment
codeforsanjose/city-agenda-scraper pull request #47
Opened 2021-09-13 00:15 UTC by dntrply

* Lauch Firefox in headless mode
* Run Use your own gmail account and use the shared drive Cities
* Note - using the Agenda Scraper account directly will no longer work
* Re-facored code into smaller functions - also helpful when hand-running the code in a Jupyter notebook

### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)

- Describe what changes are being made

- Describe why these changes are being made

- List the use cases and edge cases relevant to this PR

- Describe how errors will be handled. How will we know if this code breaks in production

- Describe any external libraries/dependencies added or removed in this PR

- Describe any security risks are there regarding this change

- Describe how you tested these changes

- Link to relevant external documentation

--------------------------
### :clipboard: Mandatory Checklist

- [x] Example of a checked item (please remove when creating your Pull Request) 

- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [ ] Have you discussed these changes with the project leader(s)?
- [ ] Do all variable and function names communicate what they do?
- [ ] Were all the changes commented and / or documented?
- [ ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
### :framed_picture: Screenshots and Screen Recordings

#### Before

#### After

--------------------------
### :blue_book: Glossary
- PR = Pull Request

2021-09-14 05:01 UTC, krammy19 requested changes

2021-09-14 05:01 UTC, krammy19 commented on Legistar_scraper/Legistar_Selenium.py
> -        link = cells[Meeting_Details_index].find_element_by_link_text('Meeting details').get_attribute('href')
I'd prefer to keep this method of scraping the meeting date & type. We previously tried the method of grabbing it from the agenda item pages: 
(meeting_name = tables[1].iloc[0,1].replace('/', '_'))  
(target_date = (tables[2].iloc[0,1]).split(' ')[0].replace('/', '-'))

However this didn't work because certain city Legistar pages would have the information indexed on different tables. We retooled the scraper to grab the meeting date and name from the general agenda page as a workaround.

2021-09-14 05:01 UTC, krammy19 commented on Legistar_scraper/Legistar_Selenium.py
> +# Grabbing meeting date from tables (for San Jose, tables[2] works, but need to make this dynamic for other cities with different table indexes)
This method may work for San Jose, but it does not work for some other cities.

2021-09-15 01:14 UTC, dntrply commented
I realize I was working of an earlier version of the files. I'd rather close this pull request and submit a new request one I am working with the most recent code.

2021-09-15 01:14 UTC, closed without merging